### PR TITLE
Tsunami Prince => Wavelength Prince

### PR DESCRIPTION
**Pull request by wgc-coder**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
wait SGgame? dangit this is the wrong branch

**Comment by HoeenCoder** [comment]
It  needs to be PRed to master as well now

**Comment by wgc-coder** [comment]
*facepalms* does this still need to be done?

**Comment by HoeenCoder** [comment]
yes

**Comment by Lycanium-Z** [comment]
oi

**Comment by HoeenCoder** [comment]
@Lycanium-Z do this on your PR if you havent already

**Pull request merged**
