### PR TITLE
S ggame

### PR DESCRIPTION
**Pull request by TheKingKaneki5**
Hello there! I'm currently trying to add Sggame to my sever! I was wondering if you might let me pull the code from here and add it!

### CODE REVIEW

**Comment by HoeenCoder** [comment]
This isn't the right way to do it. If you cloned your server with git it's easy to swap branches.
```
git fetch [my remote]
git checkout SGgame
```
should do it. `[my remote]` would be the name of the remote that points to this repo (usually `origin`).
Feel free to reply here if you have more questions.

**Comment by TheKingKaneki5** [comment]
Hello Hoeen!
 I tried to switch the branchs and tried to use the commands you gave me,
however, it did not fully work. It said it was downloading it but when I
sync'd it I didn't see any changes. Also when i try to do the comman 'git
checkout SGgame', it say that SGgame doesn't exist. Is there anyway you can
help guide me through this a little bit more? Sorry if i'm not understand
this very well I'm new to coding.

**Comment by HoeenCoder** [comment]
`git fetch` pulls change from the remote your fetching, but dosen't apply any changes unlike `git pull`. We did this to get information on the SGgame branch. try using these:
```
git fetch [my remote]
git checkout -b SGgame
```

**Comment by TheKingKaneki5** [comment]
Thank you Hoeen!
I finally got the branches switched correctly! But the server still will
not launch SGgame. Is there another part to it that I have to do? Like a
special command or part of the code i have to fix? I also have a question
about how to make all of my users alts be seprate instead of all sharing
one code, do you think you can help with that too if you're not to busy?

**Comment by HoeenCoder** [comment]
Are any of the files from SGgame there? if not screenshot the result of `git remote -v` for me so I can try and figure out whats going on. `/playalpha` should start it.

The IP merge issue is a thing with your host and not my code, I don't remember the fix.

**Comment by TheKingKaneki5** [comment]
Thank you Hoeen
I do believe all or most of the files are there in the code. However when I
type /playalpha it says the command doesnt exist. Would there be a specific
place where I should check to see if the command is there? Also thank you
anyways for the ip problem. I'll see if i can fix it with the host

**Comment by HoeenCoder** [comment]
Did you restart the server? youll need to do that before it will work.

**Comment by TheKingKaneki5** [comment]
I restarted the Server and the command still doesn't work. I don't know if
I did something wrong or if the command needs to be added or what.

**Comment by HoeenCoder** [comment]
It should be there if you have the files, im guessing you don't or they arent hooked up properly (which would be weird if the checkout worked).

**Comment by TheKingKaneki5** [comment]
I don't know if this picture helps very much but this is a recreation of
what I did. (Minus the other parts to switch the branches) As far as I can
tell I think I have all of it.

**Comment by TheKingKaneki5** [comment]
https://i.imgur.com/JutKVWL.jpg It wouldn't let me send the picture so i
had to upload it to imgur to show you

**Comment by HoeenCoder** [comment]
Contact me on discord `HoeenHero#5770` and send me a link to the glitch console

**Comment by TheKingKaneki5** [comment]
I tried to send the link to the glitch console which it then said I
couldn't send it because I do not share the server with you. Do i need to
send you an invite to the servers code first?

**Comment by HoeenCoder** [comment]
Re-read what I said above. Either way I accepted your friend request.

**Pull request closed without merging**
