### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by Volco**

### CODE REVIEW

**Comment by Mystifi** [comment]
Well, firstly, we need to add WL, Db, and Ontime to either `dev-tools/global.d.ts` or `dev-tools/globals.ts` (I need to investigate which file it should go to; I want to say the former) after TypeScripting the file; that will resolve the "Cannot find name 'WL'" errors. I'm not sure what exactly to do in terms of resolving TypeScript conflicts for `Db`. `Ontime` should have an easy annotation.

Secondly, we need to annotate a typing for `Users.ShadowBan`. This shouldn't be difficult, but this explains the plethora of errors associated with it.

**Comment by Mystifi** [comment]
On second thought, TypeScripting `Users.ShadowBan` is going to be more difficult than I thought, seeing as `Users.ShadowBan = exports;` is the final line of a plugin file. I would propose the functions to `users.js` and leaving only the commands within the file, as this will make it much easier.

**Comment by Volco** [comment]
@Mystifi are you going to do the typescript fixes in a separate pr? just curious

**Comment by Volco** [comment]
k then im just going to close this then

**Pull request closed without merging**
