### PR TITLE
Last Active: Use lastPublicMessage

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by Volco** [comment]
? 
why the close?

**Comment by DeathlyPlays** [comment]
Well showing that message failed and I don't know if it was gonna be accepted anyways....

**Comment by Volco** [comment]
the last active using public message is fine imo. i'm not 100% for the showing the last message they sent publically tho also lastPublicMessage is time :p (i was too lazy to add Time to the end it was long enough of a variable already)

**Comment by DeathlyPlays** [comment]
Hmm

**Comment by Volco** [comment]
now to just rename it lol

**Comment by Lycanium-Z** [comment]
dfe3c58e-2ee4-4de2-98d0-6875ecd29ec3

**Pull request merged**
