### PR TITLE
Create ambush.js

### PR DESCRIPTION
**Pull request by BaneOfAll**
Well, the code may have a few bugs, but it should work. I need to know how to search in a file for something.

### CODE REVIEW

**Comment by BaneOfAll** [comment]
Just checked the build log and it's nothing to do with this code. It's 

TypeError: Cannot read property '404' of undefined
    at ClientRequest.onResponse (/home/travis/build/HoeenCoder/Wavelength/node_modules/geoip-lite-country/scripts/updatedb.js:86:97)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:558:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

**Comment by HoeenCoder** [comment]
Looks like a module is causing issues, would be wise to remove it at this point. Its used in profiles.js. Ill do it later, or you can.

**Comment by HoeenCoder** [comment]
Ok, the crash with the build is fixed, take a look at the error now. I don't have time to review this now, though I assume you created some new globals/used some that don't exist on wavelength. Double check your work (and make sure its tested & works properly, not just that it dosent crash, I will be checking myself).

**Comment by Mystifi** [comment]
The build error was simply a result of the geoip module returning the same 404 error as addressed in the PR merged earlier today. This code just needs to be updated to reflect those changes and it should work fine after an overall glance.

**Comment by Mystifi** [comment]
I would nonetheless highly recommend a detailed review.

**Comment by BaneOfAll** [comment]
Not entirely sure what I'm meant to do @Mystifi @HoeenCoder you told me different things. Is this crash a result of some other pr?

**Comment by HoeenCoder** [comment]
Originally, the build failure was. The issue was fixed in #231 and I re-ran the build. Check this for the list of issues to fix. https://travis-ci.org/HoeenCoder/Wavelength/builds/507729445?utm_source=github_status&utm_medium=notification

**Comment by BaneOfAll** [comment]
@HoeenCoder I have finished this finally. Checks passed

**Comment by HoeenCoder** [comment]
On hold at this time, see https://github.com/HoeenCoder/Wavelength/projects and #240

**Comment by HoeenCoder** [comment]
Ok maybe that was a bad idea

**Comment by HoeenCoder** [comment]
We opted to drop this.

**Pull request closed without merging**
