### PR TITLE
Implement Collapsible / Multi-Polls

### PR DESCRIPTION
**Pull request by wgc-coder**

### CODE REVIEW

**Comment by wgc-coder** [comment]
all of these commits were already pushed to master besides the last one so i'm not sure why they're all here

**Comment by HoeenCoder** [comment]
I used a squash merge to merge, i suggest using different git branches for PRs than master. I can teach you how if you want, its really easy.

**Comment by wgc-coder** [comment]
i think that's probably a good idea when i get home. should i close this pr then?

**Comment by HoeenCoder** [comment]
yeah, be sure to save your code so you dont have to rewrite it though

**Pull request closed without merging**
