### PR TITLE
Implement roomevent.js

### PR DESCRIPTION
**Pull request by wgc-coder**

### CODE REVIEW

**Comment by wgc-coder** [comment]
Travis is failing because of dependencies not being installed. How do I fix this?

**Comment by HoeenCoder** [comment]
New modules need to be added to package.json

Also we depreciated and removed moment in favor of `Chat.toDurationString()`

**Comment by HoeenCoder** [comment]
also remind me to teach you git

**Comment by wgc-coder** [comment]
Okay, understandable. Will refactor UNO out and replace moment and then see where that goes.

**Comment by DeathlyPlays** [comment]
Not sure this is particularly a good idea

**Comment by wgc-coder** [comment]
Contrary to popular belief, I am alive. Will be coming back online as soon as possible. Sorry for being gone for so long, as I have been working and haven't had much access to a computer as mine broke (again).

**Comment by wgc-coder** [comment]
Will work on a refactor for this as soon as possible.

**Comment by DeathlyPlays** [comment]
👌

**Comment by HoeenCoder** [comment]
Actually, im just going to close this, I dont like the idea of merging things into a massive clunky file.

**Pull request closed without merging**
