### PR TITLE
WLSSB: Add ^Finny and ^Showdown Helper

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
I told you not to PR this yet....

**Comment by HoeenCoder** [comment]
@Lycanium-Z arent you doing this? Not sure thats why im asking.

**Comment by DeathlyPlays** [comment]
Oh, if he is I'll delete it?
I just already had the code from doing it for them on Spectra

**Comment by Lycanium-Z** [comment]
Yeah i am, i received what Shelper and Finny wanted. Also doing The Dazzler Joe

**Comment by DeathlyPlays** [comment]
Ok

**Pull request closed without merging**
