### PR TITLE
Add a Quotes System

### PR DESCRIPTION
**Pull request by DeathlyPlays**
Tested and it works :)

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
Man, now I feel I should've made a better commit for when I fixed the eslint now the creator of @TravisBuddy referenced this LOL

**Comment by wgc-coder** [comment]
not saying i don't like the plugin but doesn't the bot already do this?

**Comment by DeathlyPlays** [comment]
Like a bot does.... but this runs off the server itself

**Comment by wgc-coder** [comment]
i'm aware but if the bot already has the functionality to do so why are we adding a plugin that is doing the same thing.

**Comment by Lycanium-Z** [comment]
Yeah but at least this has a better way to handle longer quotes

**Comment by DeathlyPlays** [comment]
Well, a bot may be temporary.... This literally backs it into the server's code....

**Comment by wgc-coder** [comment]
@DeathlyPlays i get that. you've stated that. obviously you don't understand so forget it.

**Comment by DeathlyPlays** [comment]
Meh I actually made this for Dewdrop but I was just offering to share it :v If @HoeenCoder doesn't want it, then he can just close it.... Won't hurt my feelings in the slightest....

**Comment by DeathlyPlays** [comment]
I guess I'll just close it, assuming no one cares for it....

**Pull request closed without merging**
