### PR TITLE
Add Multi-Surveys

### PR DESCRIPTION
**Pull request by DeathlyPlays**
Thanks for the help @Arrays-Arr.
Anyways this is tested and ready to go!

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
Gotcha

**Comment by wgc-coder** [comment]
to make them collapsible you're going to want to use the <details> tag in your poll output.

**Comment by wgc-coder** [comment]
well this is awkward
the details tag 
apparently i should've not put the
actual tag xD

**Comment by DeathlyPlays** [comment]
Ok

**Comment by HoeenCoder** [comment]
@Arrays-Arr can you verify this is all tested and works?

**Comment by Arrays-Arr** [comment]
It's tested and works unless theres some random crash that didnt show up in testing every command and function

**Pull request merged**
