### PR TITLE
Profiles: Make Backgrounds fit to screen

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by AllianceSky-PS** [comment]
@DeathlyPlays use this instead:
`background-size: 100% 100%`
Otherwise it will repeat the background image, If the image is small.

**Comment by DeathlyPlays** [comment]
Oh? I'll test that thanks

**Comment by DeathlyPlays** [comment]
Bump @HoeenCoder

**Comment by DeathlyPlays** [comment]
nvm this is in #134

**Pull request closed without merging**
